import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DemoApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        
        <div>
        <nav>
       <Link href='/'>Home</Link>
      <Link href='/student'>Students</Link>
      
      <Link href='/courses'>Courses</Link>
      <Link href='/settings'>Settings</Link>
      </nav>
      <div>
        <h1> Welcome to Students Dashboard</h1>
      </div>
    </div>
        
{children}
      </body>
    </html>
  );
}
