import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'


export const metadata = {
  title: "Demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      >
      <body className="min-h-full flex flex-col">
        <Link href='/about'>About US</Link>
        <Link href='/login'>Login</Link>{children}</body>
    </html>
  );
}
